name: same_shop
description: "SAME Shop - Application e-commerce Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # ðŸš€ Essentials add dependencies
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  curved_navigation_bar: ^1.0.6
  geolocator: ^14.0.2
  image_picker: ^1.0.7
  permission_handler: ^12.0.1
  url_launcher: ^6.2.0  # âœ… NOUVEAU
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
    # Nouvelles
  share_plus: ^12.0.1  # Partage
  webview_flutter: ^4.7.0
  http: ^1.2.0
 

  

  # ðŸŒ Multi-langue
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # ðŸŽ¯ State management
  flutter_riverpod: ^3.2.1

  # ðŸ” Backend
  supabase_flutter: ^2.3.4


  # ðŸŽ¨ Fonts (optionnel mais pro)
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
